---

- name: Build Application
  hosts: fs[0]
  become: true
  any_errors_fatal: true
  pre_tasks:
    - name: Gather dbpass
      command: cat {{ nex_app_build_base }}/.dbpass
      register: gather_result
      when:
        - nex_app_db_pass is not defined
    
    - name: Define nex_app_db_pass
      set_fact:
        nex_app_db_pass="{{ gather_result.stdout }}"
      when:
        - nex_app_db_pass is not defined

  roles:
    - { role: "{{ nex_app }}", mode: "build" }

  post_tasks:
    - block:
       - name: Run Post Build Script
         script:
           run-build-hook.sh {{ nex_app_build_code_base }}
         become: yes
         become_user: "{{ nex_app_unix_user }}"
 
      rescue:
       - include: tasks/build/failure.yml
